sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
minio:
  access-key: minioadmin
  secret-key: minioadmin
  endpoint: http://192.168.188.128:9000
  bucket-name: sky #存储桶